name: Feature request
description: Suggest an improvement or new capability.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the idea.
        Please describe the problem and the proposed solution clearly.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: I need a faster way to filter resources by tags.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the behavior you want.
      placeholder: Add a persistent tag filter in the list header.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches?
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Mockups, references, or related issues.
