// Auto-generated by storepix - regenerate with "npx storepix types"
// Template: default

/** Device identifiers */
export type StorepixDevice =
  | 'iphone-6.9' | 'iphone-6.7' | 'iphone-6.5' | 'iphone-6.3' | 'iphone-6.1' | 'iphone-5.5' | 'iphone-4.7'
  | 'ipad-13' | 'ipad-12.9' | 'ipad-11'
  | 'android-phone' | 'android-tablet-7' | 'android-tablet-10' | 'android-wear';

/** Screenshot theme */
export type StorepixThemeMode = 'light' | 'dark';

/** Headline layout position */
export type StorepixLayout = 'top' | 'bottom';

/** Status bar style */
export type StorepixStatusBarStyle = 'light' | 'dark' | 'auto';

/** Theme configuration */
export interface StorepixTheme {
  /** Primary accent color (hex format, e.g., '#007AFF') */
  primary?: string;
  /** Font family name */
  font?: string;
  /** Background color override (minimal template) */
  background?: string;
  /** Home indicator color for light theme */
  homeIndicatorLight?: string;
  /** Home indicator color for dark theme */
  homeIndicatorDark?: string;
}

/** Status bar configuration */
export interface StorepixStatusBar {
  /** Enable status bar overlay */
  enabled?: boolean;
  /** Time to display (e.g., '9:41') */
  time?: string;
  /** Battery percentage (0-100) */
  battery?: number;
  /** Show battery percentage text */
  showBatteryPercent?: boolean;
  /** Status bar icon style */
  style?: StorepixStatusBarStyle;
}

/** Output configuration */
export interface StorepixOutput {
  /** Output directory (relative to config) */
  dir?: string;
  /** Output format */
  format?: 'png';
}

/** Base screenshot configuration (all templates) */
export interface StorepixScreenshotBase {
  /** Unique identifier for this screenshot (used in output filename) */
  id: string;
  /** Path to source screenshot image (relative to config directory) */
  source: string;
  /** Color theme for background and text */
  theme?: StorepixThemeMode;
  /** Position of headline relative to device */
  layout?: StorepixLayout;
  /** Main marketing headline */
  headline?: string;
  /** Secondary text below headline */
  subheadline?: string;
}

/** Screenshot configuration for 'default' template */
export interface StorepixScreenshot extends StorepixScreenshotBase {
  /** Custom content fields for data-storepix bindings */
  [key: string]: string | number | boolean | undefined;
}

/** Localization overrides */
export interface StorepixLocales {
  [locale: string]: {
    [screenshotId: string]: Partial<StorepixScreenshot>;
  };
}

/** Main storepix configuration */
export interface StorepixConfig {
  /** Template to use (from ./templates/) */
  template?: string;
  /** Output settings */
  output?: StorepixOutput;
  /** Device sizes to generate */
  devices?: StorepixDevice[];
  /** Theme customization (injected as CSS variables) */
  theme?: StorepixTheme;
  /** Status bar injection configuration */
  statusBar?: StorepixStatusBar;
  /** Screenshot definitions */
  screenshots: StorepixScreenshot[];
  /** Localization overrides by locale and screenshot ID */
  locales?: StorepixLocales;
}

declare const config: StorepixConfig;
export default config;
